apiVersion: v1
kind: ConfigMap
metadata:
  name: quantum-config
  namespace: quantum-processing
  labels:
    app.kubernetes.io/part-of: quantum-file-processor
data:
  AMQ_HOST: "amq-broker"
  AMQ_PORT: "61616"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  CHUNK_SIZE: "10000"
  CONSUMER_CONCURRENCY: "1-5"
  CONSUMER_PREFETCH: "10"
  QUEUE_POLL_INTERVAL: "15000"
